spring:
  mvc:
    view:
      prefix: /
      suffix: .html

  thymeleaf:
    prefix: classpath:/templates/

server:
  port: 8080
  servlet:
    session:
      timeout: 1800s
    context-path: /

fdfs:
  so-timeout: 1500
  connect-timeout: 600
  #  thumb-image:             #缩略图生成参数
  #    width: 150
  #    height: 150
  tracker-list:            #TrackerList参数,支持多个
    - 10.138.30.58:22122
      #  pool:
      #从池中借出的对象的最大数目
    #    max-total: 153
    #获取连接时的最大等待毫秒数100
#    max-wait-millis: 102
